0.2.4: Update AES dependencies (aes 0.3 is dead)
Problem: `cargo build` gives an error.
```
error: failed to select a version for the requirement `aes = "^0.3"`
candidate versions found which didn't match: 0.7.4, 0.7.3, 0.7.2, ...
location searched: crates.io index
required by package `aes-gcm v0.5.0`
```